import "@/app/globals.css";
import styles from "./layout.module.css";
import Link from "next/link";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={styles.body}>
          <nav className={styles.topNav}>
            <div className={styles.topNavLeft}>
              <div className="appLogo"></div>
              <input type="text" />
            </div>
            <div className={styles.topNavCenter}>
              <Link href="/?page=1">
                <div>⌂</div>
              </Link>
              <Link href="/videos">
                <div>📷</div>
              </Link>
            </div>
            <div className={styles.topNavRight}>
              <Link href="">
                <div>✉</div>
              </Link>
              <Link href="">
                <div>🔔</div>
              </Link>
              <Link href="/api/auth/logout">
                <div>Log Out</div>
              </Link>
            </div>
          </nav>
          <div className={styles.root}>{children}</div>
        </body>
      </UserProvider>
    </html>
  );
}
